services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    privileged: true

  bpfpgpool:
    image: bpfpgpool
    build:
      context: .
      target: bpfpgpool-debug
    container_name: bpfpgpool
    environment:
      # https://hub.docker.com/r/bitnami/pgbouncer/
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PASSWORD: postgres
      PGBOUNCER_MIN_POOL_SIZE: 5
      PGBOUNCER_DEFAULT_POOL_SIZE: 10
      PGBOUNCER_AUTH_TYPE: trust
    privileged: true
    ports:
      - 6432:6432
