services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    network_mode: host

  bpfpgpool-pgbouncer:
    build:
      context: .
      target: bpfpgpool-pgbouncer
    container_name: bpfpgpool-pgbouncer
    environment:
      # https://hub.docker.com/r/bitnami/pgbouncer/
      POSTGRESQL_HOST: "10.121.240.151"
      POSTGRESQL_USERNAME: bpfpgpool
      POSTGRESQL_PASSWORD: bpfpgpool
      POSTGRESQL_DATABASE: bpfpgpool
      PGBOUNCER_DATABASE: bpfpgpool
      PGBOUNCER_MIN_POOL_SIZE: 1
      PGBOUNCER_DEFAULT_POOL_SIZE: 10
      PGBOUNCER_IGNORE_STARTUP_PARAMETERS: extra_float_digits
      PGBOUNCER_EXTRA_FLAGS: --verbose
      ENABLE_BPF: true
      ENABLE_TSHARK: true
    image: bpfpgpool:pgbouncer
    privileged: true
    network_mode: host
    volumes:
      - ./scripts/pgbouncer:/docker-entrypoint-initdb.d

  bpfpgpool-pgcat:
    build:
      context: .
      target: bpfpgpool-pgcat
    container_name: bpfpgpool-pgcat
    environment:
      RUST_LOG: trace
      ENABLE_BPF: true
      # ENABLE_TSHARK: true
      BPF_LOAD_PAIRS: false
    image: bpfpgpool:pgcat
    privileged: true
    volumes:
      - ./conf/pgcat.toml:/etc/pgcat/pgcat.toml
    network_mode: host

  bpfpgpool-pgclient-1:
    build:
      context: .
      target: bpfpgpool-pgclient
    image: bpfpgpool:pgclient
    restart: always
    network_mode: host

  # bpfpgpool-pgclient-2:
  #   build:
  #     context: .
  #     target: bpfpgpool-pgclient
  #   image: bpfpgpool:pgclient
  #   restart: always

  # bpfpgpool-pgclient-3:
  #   build:
  #     context: .
  #     target: bpfpgpool-pgclient
  #   image: bpfpgpool:pgclient
  #   restart: always
