#
# PgCat config example.
#

#
# General pooler settings
[general]
# What IP to run on, 0.0.0.0 means accessible from everywhere.
host = "0.0.0.0"

# Port to run on, same as PgBouncer used in this example.
port = 6432

# Whether to enable prometheus exporter or not.
enable_prometheus_exporter = false

# Port at which prometheus exporter listens on.
prometheus_exporter_port = 9930

# How long to wait before aborting a server connection (ms).
connect_timeout = 5000

# How much time to give `SELECT 1` health check query to return with a result (ms).
healthcheck_timeout = 1000

# How long to keep connection available for immediate re-use, without running a healthcheck query on it
healthcheck_delay = 30000

# How much time to give clients during shutdown before forcibly killing client connections (ms).
shutdown_timeout = 60000

# For how long to ban a server if it fails a health check (seconds).
ban_time = 60 # seconds

# If we should log client connections
log_client_connections = true

# If we should log client disconnections
log_client_disconnections = true

# TLS
# tls_certificate = "server.cert"
# tls_private_key = "server.key"

# Credentials to access the virtual administrative database (pgbouncer or pgcat)
# Connecting to that database allows running commands like `SHOW POOLS`, `SHOW DATABASES`, etc..
admin_username = "postgres"
admin_password = "postgres"

# pool
# configs are structured as pool.<pool_name>
# the pool_name is what clients use as database name when connecting
# For the example below a client can connect using "postgres://sharding_user:sharding_user@pgcat_host:pgcat_port/sharded"
[pools.test_pgcat]
pool_mode = "transaction"
default_role = "any"
query_parser_enabled = false
primary_reads_enabled = false
sharding_function = "pg_bigint_hash"

[pools.test_pgcat.users.0]
username = "postgres"
password = "password"

pool_size = 9
min_pool_size = 0
statement_timeout = 0

# Shard 0
[pools.test_pgcat.shards.0]
servers = [
	[ "10.121.240.168", 5432, "primary" ],
]
database = "test_pgcat"

[pools.test_bpf_pgcat]
pool_mode = "transaction"
default_role = "any"
query_parser_enabled = false
primary_reads_enabled = false
sharding_function = "pg_bigint_hash"

[pools.test_bpf_pgcat.users.0]
username = "postgres"
password = "password"

pool_size = 9
min_pool_size = 0
statement_timeout = 0

[pools.test_bpf_pgcat.shards.0]
servers = [
	[ "10.121.240.168", 5432, "primary" ],
]
database = "test_bpf_pgcat"
