// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfClientState struct {
	Valid  uint8
	_      [3]byte
	Server bpfSocket4Tuple
}

type bpfServerState struct {
	Valid    uint8
	_        [3]byte
	Client   bpfSocket4Tuple
	Prepared [256][64]uint8
}

type bpfSocket4Tuple struct {
	LocalIp4   uint32
	LocalPort  uint32
	RemoteIp4  uint32
	RemotePort uint32
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	SkSkbStreamVerdictProgPool *ebpf.ProgramSpec `ebpf:"sk_skb_stream_verdict_prog_pool"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ClientStates *ebpf.MapSpec `ebpf:"client_states"`
	ServerStates *ebpf.MapSpec `ebpf:"server_states"`
	Servers      *ebpf.MapSpec `ebpf:"servers"`
	Sockhash     *ebpf.MapSpec `ebpf:"sockhash"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ClientStates *ebpf.Map `ebpf:"client_states"`
	ServerStates *ebpf.Map `ebpf:"server_states"`
	Servers      *ebpf.Map `ebpf:"servers"`
	Sockhash     *ebpf.Map `ebpf:"sockhash"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ClientStates,
		m.ServerStates,
		m.Servers,
		m.Sockhash,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	SkSkbStreamVerdictProgPool *ebpf.Program `ebpf:"sk_skb_stream_verdict_prog_pool"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.SkSkbStreamVerdictProgPool,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
